services:
  pixel-vista:
    container_name: pixel-vista
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:3000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
